### ISSUE TITLE
Choose a license for this library

### ISSUE THREAD

**Issue by nickerso** [sys-bio/libsemsim#6]
Should choose an appropriate license for this library. There is a branch that looks to be applying the MIT license, not sure if that was intended to be merged in?

**Comment by CiaranWelsh** [comment]
Good question. Which licence do you think is best? 

https://choosealicense.com/

**Comment by nickerso** [comment]
My default choice is Apache 2.0 unless there is a reason not to.

**Comment by CiaranWelsh** [comment]
Sounds good
