### ISSUE TITLE
Cannot install pip package on linux via pypi, python 3.6.9

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/libsemsim#7]
I just tried to install this via pip and saw the package on pip
https://pypi.org/project/libsemsim/#history
But no version which can be installed can be found
```
(kinan) mkoenig@prime1:~/git/kinetic_annotations$ pip install libsemsim
Collecting libsemsim
  ERROR: Could not find a version that satisfies the requirement libsemsim (from versions: none)
ERROR: No matching distribution found for libsemsim

(kinan) mkoenig@prime1:~/git/kinetic_annotations$ python
Python 3.6.9 (default, Jul  3 2019, 15:36:16) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by CiaranWelsh** [comment]
This issue is no longer relevant because the the package has been redesigned from the ground up. I'm still developing the c++ end but hope to get working on the Python front end shortly.

**Comment by matthiaskoenig** [comment]
@CiaranWelsh Let me know if you have a working python version/binding. I am very interested in using the library, but would only interact via python with it.
Best M
